// basic action types 
export const ADD_INGRIDIENT = "ADD_INGRIDIENT";
export const REMOVE_INGRIDIENT = "REMOVE_INGRIDIENT";
export const SET_INGRIDIENTS = 'SET_INGRIDIENTS'; 
export const FETCH_INGRIDIENTS_FALIED = "FETCH_INGRIDIENTS_FALIED"; 
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'; 
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'; 